### PR TITLE
Win32

### PR DESCRIPTION
**Pull request by r-lyeh-archived**
forgot to pull yesterday O:)

### CODE REVIEW

**Comment by rikusalminen** [comment]
I added a ton of comments about things I need you to fix before this moves forward. You can fix the issues in new commit(s), you don't have to go back and modify the commits, that's just painful.

You also need to add your full real name to LICENSE file.

Your commit messages are quite messy and the git history is quite fucked up. But don't worry, let's fix it using rebase/squash before merging this to master. Note: my commit messages in the win32 branch are messy too, because it was intended that I rebase/squash that before it goes to master.

**Comment by rikusalminen** [comment]
I have merged your work and cleaned up the patch and the git history a little bit. The result is in https://github.com/rikusalminen/glwt/tree/win32

I still want you to do the following things before this goes to master:
1) take the MSVC commit, make sure EGL code also builds on MSVC, you can compile EGL without anything installed but you can't link it. if it compiles, it's fine. add your full real name to LICENSE file and commit author. add the changes to the commit with git commit --amend --reset-author.
2) rebase the event handling commit on top of the MSVC commit.

In the end I want to have 3 commits, my win32 initialization, msvc cleanup, win32 event handling, which I'll merge to master.

**Comment by r-lyeh-archived** [comment]
ok. made the EGL to compile. both EGL and WGL refuse to link now. compiler cant find 'm.lib' at link stage. where is the new m.lib dependency located in the makefiles? I cant find it

**Comment by rikusalminen** [comment]
Where is the code? I can't find it in GitHub?

The problem is CMakeLists.txt line 46. It says: link_libraries(m)

You need to link with -lm if you use the math library on Linux and some other unixes too, but that's just accidentally left over from trying out an older test case.

I'll fix that, you can meanwhile remove that line.

EGL code should not link anyway, but it should compile. Does it do so now?

**Comment by r-lyeh-archived** [comment]
Ah right. There it was. Yep, after a few changes EGL compiles and doesnt link, and WGL both compiles and links.

**Comment by rikusalminen** [comment]
Could you please share your MSVC/EGL work so we can move forward with merging this?

**Comment by rikusalminen** [comment]
On IRC, you mentioned some problems with *W WinAPI functions. Can you try if adding -DUNICODE to your compiler command line helps? Using ascii-only *A functions is not an option, full unicode support is a must.

You can do this in CMakeLists.txt with something like

```
if(WIN32)
  add_definitions(-DUNICODE)
endif()
```

**Pull request closed without merging**
