### PR TITLE
Implemented the OSX port.

### PR DESCRIPTION
**Pull request by jansol**

### CODE REVIEW

**Comment by jansol** [comment]
Updated window creation to simplify glwtShowWindow

**Comment by jansol** [comment]
Fixed mouse event nonsense.

**Comment by scoopr** [comment]
LGTM.
At least events that come from the events test all look sane to me, can't see any obvious issues with the code.

**Comment by jansol** [comment]
(Just a small code cleanup: removed a couple of unnecessary variables from pixel format creation)

**Comment by rikusalminen** [comment]
Merged to master.

**Pull request closed without merging**
